### PR TITLE
KAIZ 145 - Participants LIst + Preview

### PR DESCRIPTION
**Pull request by LPZ-Fabian**
New Changes:
- Functional participants preview at the bottom of the page
- Participants list popover showing names + mic status

Updates:
- UseHms: Updated composable to retrieve list of peers with audio status flag attribute

### CODE REVIEW

**Review by jasjot1 — COMMENTED** [review]
Can you use the same icon for the user in the PodHeader?

**Comment by VictorSeverin** [comment]
LGTM!
Don't forger to resolve conflicts

**Review by VictorSeverin — APPROVED** [review]
LGTM!
Don't forger to resolve conflicts

**Review by jasjot1 — APPROVED** [review]
LGTM

**Pull request merged**
